#[[plugins]]
#repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = "neoclide/coc.nvim"
merge = 0

[[plugins]]
repo = "fatih/vim-go"

[[plugins]]
repo = "rust-lang/rust.vim"

[[plugins]]
repo = "cocopon/iceberg.vim"

[[plugins]]
repo = "jacoloves/timestampMemo.vim"

[[plugins]]
repo = "nanotech/jellybeans.vim"

[[plugins]]
repo = "dracula/vim"
name = "dracula"

[[plugins]]
repo = "ryanoasis/vim-devicons"

